name: bagam_check
description: Aplicativo de checklist para caminhões tanque da BAGAM.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Pacotes estáveis e compatíveis:
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  flutter_email_sender: ^7.0.0
  share_plus: ^7.2.1
  pdf: ^3.10.4
  open_filex: ^4.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  signature: ^6.3.0
  file_picker: ^10.2.0
  intl: ^0.20.2
  uuid: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
